# Generated by Django 3.0.7 on 2020-12-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='city',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='college',
            field=models.CharField(default='VIT Chennai', max_length=100),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='tagline',
            field=models.CharField(default='Hit me at Above Belly!', max_length=200),
        ),
    ]
